
USE [master]
GO

/****** Object:  Database [Northwind]    Script Date: 21/10/2020 5:10:12 p. m. ******/
CREATE DATABASE [Northwind]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Northwind', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Northwind.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Northwind_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Northwind_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Northwind] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Northwind].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Northwind] SET ANSI_NULL_DEFAULT ON
GO

ALTER DATABASE [Northwind] SET ANSI_NULLS ON
GO

ALTER DATABASE [Northwind] SET ANSI_PADDING ON
GO

ALTER DATABASE [Northwind] SET ANSI_WARNINGS ON
GO

ALTER DATABASE [Northwind] SET ARITHABORT ON
GO

ALTER DATABASE [Northwind] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Northwind] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Northwind] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Northwind] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Northwind] SET CURSOR_DEFAULT  LOCAL
GO

ALTER DATABASE [Northwind] SET CONCAT_NULL_YIELDS_NULL ON
GO

ALTER DATABASE [Northwind] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Northwind] SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE [Northwind] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Northwind] SET  DISABLE_BROKER
GO

ALTER DATABASE [Northwind] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Northwind] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Northwind] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Northwind] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Northwind] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Northwind] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Northwind] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Northwind] SET RECOVERY FULL
GO

ALTER DATABASE [Northwind] SET  MULTI_USER
GO

ALTER DATABASE [Northwind] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [Northwind] SET DB_CHAINING OFF
GO

ALTER DATABASE [Northwind] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Northwind] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Northwind] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'Northwind', N'ON'
GO

ALTER DATABASE [Northwind] SET QUERY_STORE = OFF
GO

USE [Northwind]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Order]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[OrderItem]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Product]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Supplier]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[User]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

/****** Object:  StoredProcedure [dbo].[CustomerPagedList]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[ValidateUser]    Script Date: 21/10/2020 5:10:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [Northwind] SET  READ_WRITE
GO
